---
title: "Punto 3 TALLER INTERPOLACIÓN"

output: html_notebook
---
###Johan Daniel Ortegon Parra
###Ricardo Riscanevo
3. Sea $f(x)=e^{x}$ en el intervalo [0,1]
a. Tabular varios puntos y grafíquelos
```{r}
library(PolynomF)
x<-c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)
y<-c(1.10517,1.22140,1.34986,1.49182,1.64872,1.82212,2.01375,2.22554,2.45960,2.71828)
datosX = x[1:5]
datosY = y[1:5]
interpolacionLagrange = poly.calc(datosX,datosY)
interpolacionLagrange
plot(x,y,col="red", xlim=c(0,0.8), ylim=c(1,2))
par(new=TRUE)
curve(interpolacionLagrange,add=T,xlim=c(0,0.8), ylim=c(1,2))
```
b. Interpolar con el método de Lagrange
c. Utilizando 8 cifras decimales o más, en cada entrada, determine el tamaño
del paso que me produzca un error por debajo de $10^{-6}$
Dada la teoria de la cota de error de la interpolacion de Lagrange: $\frac{f^{n+1}(\xi(x))}{(n+1)!}\prod_{i=0}^{n}(x-x_{i})$
```{r}
x<-c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)
n = 9
funcionDerivada = exp(1)
resultadoFactorial = factorial(n+1)
resultadoFactorial

resta = function(x) 1.5-x
eval(resta(1.5))
productoria=1
for(i in 0:n+1)
{
  cat("X:",x[i])
  productoria = productoria*(eval(resta(x[i])))
}
productoria
cotaDeError=(funcionDerivada/resultadoFactorial)*productoria
cotaDeError
```
